2021-08-02 14:37:21,077 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:37:43,318 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:37:56,551 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:38:39,522 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:38:48,001 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:39:02,355 ERROR: Exception on /auth/login [POST] [in c:\flask_template\project_template\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\ext\declarative\clsregistry.py", line 322, in _resolve_name
    rval = d[token]
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\util\_collections.py", line 729, in __missing__
    self[key] = val = self.creator(key)
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\ext\declarative\clsregistry.py", line 301, in _access_cls
    return self.fallback[key]
KeyError: 'Session'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\flask_template\project_template\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\flask_template\project_template\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\flask_template\project_template\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\flask_template\project_template\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\flask_template\project_template\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\flask_template\project_template\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\flask_template\app\auth\routes.py", line 16, in login
    user = User.query.filter_by(username=form.username.data).first()
  File "c:\flask_template\project_template\lib\site-packages\flask_sqlalchemy\__init__.py", line 512, in __get__
    mapper = orm.class_mapper(type)
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\orm\base.py", line 451, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\orm\base.py", line 430, in _inspect_mapped_class
    mapper._configure_all()
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\orm\mapper.py", line 1352, in _configure_all
    configure_mappers()
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\orm\mapper.py", line 3299, in configure_mappers
    mapper._post_configure_properties()
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\orm\mapper.py", line 1965, in _post_configure_properties
    prop.init()
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\orm\interfaces.py", line 197, in init
    self.do_init()
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\orm\relationships.py", line 2077, in do_init
    self._process_dependent_arguments()
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\orm\relationships.py", line 2148, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\util\langhelpers.py", line 893, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\orm\relationships.py", line 2044, in entity
    argument = self.argument()
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\ext\declarative\clsregistry.py", line 326, in _resolve_name
    self._raise_for_name(name, err)
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\ext\declarative\clsregistry.py", line 312, in _raise_for_name
    from_=err,
  File "c:\flask_template\project_template\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->user, expression 'Session' failed to locate a name ('Session'). If this is a class name, consider adding this relationship() to the <class 'app.models.User'> class after both dependent classes have been defined.
2021-08-02 14:39:30,401 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:39:31,116 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:40:01,223 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:40:43,497 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:45:14,852 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:45:30,367 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:46:55,272 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:54:01,171 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:54:14,382 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:55:12,955 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 14:55:51,808 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 15:11:57,429 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 15:12:06,994 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 15:12:28,716 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 15:12:35,879 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 15:12:41,402 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 15:12:42,102 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
2021-08-02 15:31:37,013 INFO: Project Template startup [in C:\flask_template\app\__init__.py:52]
